name: Linux GCC

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-gcc
  cancel-in-progress: true

jobs:
  library:
    name: GNU@9.3 C++17 Release
    runs-on: ubuntu-20.04
    # env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual"}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Dependencies
      run: .github/workflows/dependencies/dependencies.sh

    - name: Configure Project and Generate Build System
      run: |
        cmake \
          -B${{runner.workspace}}/ROMSX/build \
          -DCMAKE_INSTALL_PREFIX:PATH=${{runner.workspace}}/ROMSX/install \
          -DCMAKE_BUILD_TYPE:STRING=Debug \
          -DROMSX_DIM:STRING=3 \
          -DROMSX_ENABLE_MPI:BOOL=ON \
          -DROMSX_ENABLE_TESTS:BOOL=ON \
          -DROMSX_ENABLE_ALL_WARNINGS:BOOL=ON \
          -DROMSX_ENABLE_FCOMPARE:BOOL=ON \
          ${{github.workspace}};

    - name: Compile and Link
      run: |
        cmake --build ${{runner.workspace}}/ROMSX/build --parallel 2 --verbose

    - name: CMake Tests # see file ROMSX/Tests/CTestList.cmake
      run: |
        ctest
      working-directory: ${{runner.workspace}}/ROMSX/build
